// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

import './Bio.css';
;

function Bio$Exhibition(Props) {
  var data = Props.data;
  var $$location = data.location !== "" ? ", " + data.location : "";
  var city = data.city !== "" ? ", " + data.city : "";
  var country = data.country !== "" ? ", " + data.country : "";
  var place = $$location + city + country;
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "bioYear largeText"
                }, data.year), React.createElement("p", {
                  className: "exhibitionInfo smallText"
                }, data.title, ", ", React.createElement("i", undefined, data.description), place, React.createElement("br", undefined)));
}

var Exhibition = {
  make: Bio$Exhibition
};

function Bio$CV(Props) {
  var cv = Props.cv;
  cv.map(function (x) {
        return x.year;
      });
  var result = cv.map(function (x) {
        return React.createElement(Bio$Exhibition, {
                    data: x
                  });
      });
  return React.createElement("div", undefined, result, React.createElement("br", undefined), React.createElement("br", undefined));
}

var CV = {
  make: Bio$CV
};

function Bio$Bio(Props) {
  var cv = Props.cv;
  console.log(Caml_array.get(cv, 0));
  return React.createElement("div", {
              id: "bioContainer"
            }, React.createElement("div", undefined, React.createElement("div", {
                      className: "bioHeader largeText"
                    }, "BIO"), React.createElement("p", {
                      className: "bioText largeText"
                    }, "Since Danish sculptor Carl Emil Jacobsen (b. 1987) graduated from Kolding School of Design in 2012, his practice has oscillated between art and design, revol&shy;ving around existentialism, ritualistic sophisti&shy;cation and solid craftsmanship."), React.createElement("p", {
                      className: "bioText largeText"
                    }, "Working with found materials such as stones from the heath, bricks from demolished buildings, chalk&shy;stone and marble, Carl Emil Jacobsen trans&shy;forms massive stones into light, thin and crisp shells of fine colour. As an ode to the richness of natural colours in the Nordic landscape, he brings new life to the powdered stone by converting it into layers of poetic coloured pigment — in bright to burnt hues — and a sculptural element in itself. His iron sculp&shy;tures, some polished, some burnt,  are created intuitively out of welding work without preliminary studies resulting in fragmented pieces hammered together to instinctive forms."), React.createElement("p", {
                      className: "bioText largeText"
                    }, "Inspired by the dictum of late Danish sculptor Willy Ørskov's theory that \"the content of the sculpture  is sculpture\", his nonfigurative sculp&shy;tures exist  on their own terms as abstract, physical forms fostering experiential connection over intellectual interference in the elastic borderland between nature and culture."), React.createElement("p", {
                      className: "bioText textEnd largeText"
                    }, "Carl Emil Jacobsen is represented by Galerie Maria Wettergren in Paris and has been exhibited at Art Basel, PAD, Clay Museum of Ceramic Art Denmark, Mindcraft Exhibition in Milan, Patrick Parrish Gallery, Chamber Gallery, Kunsthal Charlottenborg, Piscine and elsewhere.")), React.createElement("div", undefined, React.createElement("div", {
                      className: "bioHeader largeText"
                    }, React.createElement("p", {
                          className: "bioHeader largeText"
                        }, "SELECTED", React.createElement("br", undefined), "EXHIBITIONS")), React.createElement(Bio$CV, {
                      cv: cv
                    }), React.createElement("div", {
                      className: "xEnd largeText"
                    }, "X")));
}

var Bio = {
  make: Bio$Bio
};

export {
  Exhibition ,
  CV ,
  Bio ,
}
/*  Not a pure module */
