// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Downloads from "../downloads/Downloads.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

import './Main.css';
import MyHeader from '../header/MyHeader.jsx';
import Bio from '../bio/Bio';
import InstagramDisplay from '../instagram/InstagramDisplay.jsx';
import SimpleSlider from "../slider/SimpleSlider";
import { fetch_slider_pics2, fetch_home_pic2, fetch_cv_file2 } from "./fetchDropBoxFiles";
;

async function fetch_slider_pics(setSilderPics) {
  var slier_pics = await (fetch_slider_pics2());
  return Curry._1(setSilderPics, (function (param) {
                return slier_pics;
              }));
}

async function fetch_home_pic(setHomePic) {
  var pic = await (fetch_home_pic2());
  return Curry._1(setHomePic, (function (param) {
                return pic;
              }));
}

async function fetch_cv_file(setCvFile) {
  return Curry._1(setCvFile, await (fetch_cv_file2()));
}

function Main$Main(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = React.useState(function () {
        return "";
      });
  var setHomePic = match[1];
  var homepic = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setdbImgs = match$1[1];
  var dbImgs = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setCv = match$2[1];
  React.useEffect((function () {
          console.log("" + homepic + "");
          fetch_home_pic(setHomePic);
          console.log("" + dbImgs.toString() + "");
          fetch_slider_pics(setdbImgs);
          fetch_cv_file(setCv);
        }), []);
  var match$3 = url.path;
  var tmp;
  var exit = 0;
  if (match$3) {
    switch (match$3.hd) {
      case "" :
          if (match$3.tl) {
            exit = 1;
          } else {
            tmp = (<InstagramDisplay igImg={homepic} key={homepic} />);
          }
          break;
      case "archive" :
          if (match$3.tl) {
            exit = 1;
          } else {
            tmp = (<SimpleSlider dbImgs={dbImgs} />);
          }
          break;
      case "bio" :
          if (match$3.tl) {
            exit = 1;
          } else {
            tmp = (<Bio />);
          }
          break;
      case "downloads" :
          if (match$3.tl) {
            exit = 1;
          } else {
            tmp = React.createElement(Downloads.Downloads.make, {
                  pdf: ""
                });
          }
          break;
      default:
        exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    tmp = (<InstagramDisplay igImg={homepic} key={homepic} />);
  }
  return React.createElement("div", {
              className: "mainContainer"
            }, (<MyHeader />), React.createElement("div", {
                  id: "contentBox"
                }, tmp));
}

var Main = {
  make: Main$Main
};

export {
  fetch_slider_pics ,
  fetch_home_pic ,
  fetch_cv_file ,
  Main ,
}
/*  Not a pure module */
