// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './Downloads.css'
;

function Downloads$Downloads(Props) {
  var pdf = Props.pdf;
  return React.createElement("div", {
              id: "dlContainer"
            }, React.createElement("a", {
                  className: "pdfDL largeText",
                  download: pdf,
                  href: pdf
                }, "CEJ_works.pdf"));
}

var Downloads = {
  make: Downloads$Downloads
};

export {
  Downloads ,
}
/*  Not a pure module */
